addpaths;

[test_result, mdp_params, reward] = runtest(...
    'ame',struct(),...
    'obstacle_',struct(),...
    struct(...
        'training_samples',16,...
        'verbosity',1));

% Visualize solution.
visualize(test_result, mdp_params, reward);
