addpaths;

naive_table = struct('bool', true,...
                     'rho_bound', [1;8],...
                     'sf_bound', [0.9;1.6],...
                     'cell', 10);

[test_result, mdp_params, reward] = runtest(...
    'ame',struct(),...
    'obstacle_',struct('naive_table', naive_table),...
    struct(...
        'training_samples',16,...
        'verbosity',1));

% Visualize solution.
visualize(test_result, mdp_params, reward);
